package com.howin.qiulu.pojo;
import java.sql.Timestamp;
import java.util.Date;

// default package
// Generated 2017-4-11 16:17:51 by Hibernate Tools 3.2.1.GA

/**
 * EvaluationResult generated by hbm2java
 */
public class EvaluationResult implements java.io.Serializable {

	private EvaluationResultId id;
	private Integer commodityScore;
	private Date time;
	private String image;
	private String content;
	private Integer type;
	private Integer etype;
	private Date createTime;
	private String username;
	private Integer userId;
	private String headPort;
	public EvaluationResult() {
	}

	public EvaluationResult(EvaluationResultId id, Integer commodityScore, Date time, String image, String content,
			Integer type, Integer etype, Date createTime, String username, Integer userId, String headPort) {
		super();
		this.id = id;
		this.commodityScore = commodityScore;
		this.time = time;
		this.image = image;
		this.content = content;
		this.type = type;
		this.etype = etype;
		this.createTime = createTime;
		this.username = username;
		this.userId = userId;
		this.headPort = headPort;
	}





	public EvaluationResult(EvaluationResultId id) {
		this.id = id;
	}

	public EvaluationResultId getId() {
		return this.id;
	}

	public void setId(EvaluationResultId id) {
		this.id = id;
	}

	public Integer getCommodityScore() {
		return commodityScore;
	}

	public void setCommodityScore(Integer commodityScore) {
		this.commodityScore = commodityScore;
	}

	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}


	public Integer getType() {
		return type;
	}


	public void setType(Integer type) {
		this.type = type;
	}


	public Integer getEtype() {
		return etype;
	}


	public void setEtype(Integer etype) {
		this.etype = etype;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getHeadPort() {
		return headPort;
	}

	public void setHeadPort(String headPort) {
		this.headPort = headPort;
	}
	
	 
}
